[package]
name = "the_macavei_post"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.yew]
version = "0.21.0"
features = ["csr"]
image = "0.24.2"
gloo = "0.8.0"